### ISSUE TITLE
[Bug]: Crash when starting world

### ISSUE THREAD

**Issue by ellamoon555** [Zepalesque/Aether-Redux-Issue-Tracker#146] opened 2024-11-04 17:12 UTC
### Minecraft Version

1.19.2

### Redux Version

2.0.17

### Aether Version

1.5.0

### Forge/Neoforge Version

43.4.2

### What happened?

The game will start up normally, but when I try to open a world it will instantly crash. It happens with both new and old worlds, and I have tested it outside my modpack with just this mod and The Aether and got the same result.

### What was the expected result?

The world starts normally, and I can play as usual.

### Steps to Reproduce

Try to start a world with The Aether version: 1.5.0 and The Aether Redux version: 2.0.17 installed

### Log Output (if applicable)

[latest.log](https://github.com/user-attachments/files/17621618/latest.log)

### Crash Report (if applicable)

[crash-2024-11-04_12.10.55-client.txt](https://github.com/user-attachments/files/17621627/crash-2024-11-04_12.10.55-client.txt)

### Make sure to confirm these as well before submitting the report:

- [X] The issue persists on the latest version of the mod.
- [X] All version numbers are properly recorded, no instances of ‘latest’
- [X] All details are reported clearly and concisely
- [X] This issue is not a duplicate of another issue
- [X] If the issue is a modpack-related issue, it only occurs *with* Redux installed, and not without
- [X] If the issue is a modpack-related issue, it has been reported to the modpack devs as well

**Comment by Zepalesque** [comment] 2024-11-06 02:28
*technically* a duplicate of #143 (which in itself is a duplicate of #142, but works as a 1.19.2 tracker of the issue) but I had closed that one before so its understandable if you didnt see that

if/when i get around to backporting v2.0.18's fixes to 1.19.2 then this will be fixed by that

**Closed as completed by Zepalesque** 2024-11-06 02:28 UTC
Labels: bug-report, duplicate
