### ISSUE TITLE
Bug [1.20.1]: Game crashes when installed alongside Sinytra Connector/Forgified Fabric API (FFAPI)

### ISSUE THREAD

**Issue by Biokoro** [Zepalesque/Aether-Redux-Issue-Tracker#26] opened 2023-11-01 22:17 UTC
**What version of the mod, Forge/Neoforge and Minecraft are you using?**
Mod version: aether-redux-1.3-1.20.1-neoforge
Forge version: 47.1.3 (The only version Sinytra Connector can run on)
Minecraft version: 1.20.1

**Describe the bug**
Running the game with Aether Redux and Sinytra Connector/FFAPI causes the game to crash

**To Reproduce**
1. Run Forge version 47.1.3
2. Add Aether version "aether-1.20.1-1.0.0-beta.1.4-neoforge"
3. Add Aether Redux version "Release 1.3"
4. Add Sinytra Connector version "Connector-1.0.0-beta.22+1.20.1-full"
5. Add Forgified Fabric API version "fabric-api-0.90.4+1.9.30+1.20.1"

**Expected behavior**
Game should launch to the menu screen and play like normal

**Crash report**
[crash-2023-11-01_17.09.04-client.txt](https://github.com/Zepalesque/Aether-Redux-Issue-Tracker/files/13232223/crash-2023-11-01_17.09.04-client.txt)

**Log file**
[latest.log](https://github.com/Zepalesque/Aether-Redux-Issue-Tracker/files/13232229/latest.log)

**Additional context**
Despite the file being called "fabric-api", it is for forge. Sinytra Connector and Forgified Fabric API is a way for fabric mods to run on forge.
It's not perfect, and whether things work or not is entirely up to user error, but I've never had something hard crash while simply booting up the game before.
This crash happened running the game with only the mods listed in the "To Reproduce" section.
No other mods were added, neither fabric or forge.
Without Sinytra Connector and FFAPI, the game boots up without any issues

Apologies if I got anything wrong, I'm not too experienced at using GitHub.

**Comment by Biokoro** [comment] 2023-11-02 23:58
Can confirm that this is only happening with "aether-redux-1.3-1.20.1-neoforge".
Downgrading Aether Redux to "aether-redux-1.2-1.20.1-neoforge" allows the game to boot up just fine.

**Comment by Liamgrayskull** [comment] 2023-11-04 23:50
Can confirm that the same issue is occurring for me when replicated

**Comment by Zepalesque** [comment] 2023-11-05 03:51
hmm, from what I can tell it seems like this is being caused by a mixin that I accidentially added an invalid argument to, and somehow sinytra connector is making it crash. not sure why *sinytra connector* is making it happen, rather than it *always* happening, but I’ll fix this for 1.4 regardless lol

**Comment by Zepalesque** [comment] 2023-11-08 04:04
should be fixed as of 1.3.1

**Closed by Zepalesque** 2023-11-08 04:04 UTC
Labels: bug-report
