### ISSUE TITLE
[Bug]: Aether Redux trees not dropping saplings

### ISSUE THREAD

**Issue by MoonMoonShark** [Zepalesque/Aether-Redux-Issue-Tracker#55] opened 2024-01-30 00:18 UTC
### Minecraft Version

1.19.2

### Mod Version

1.3.4

### Forge/Neoforge Version

43.3.30

### What happened?

hey there! when we cut down aether: redux trees, they don't drop saplings. i've felled entire forests, with no saplings.

### What was the expected result?

ideally, the trees would eventually drop saplings.

### Steps to Reproduce

cut down trees

### Additional Context/Information

i seem to be getting saplings from The Aether trees, but not from Aether: Redux. i know you've said you're only doing one last version of the mod for 1.19.2, but i really hope you can squeeze this in there. pretty pretty please. yagroot is gorgeous and we'd really like to build with it, without deforesting the entire aether.

thank you for everything! please let me know if there is anything i can do to help.

### Make sure to confirm these as well before submitting the report:

- [X] The issue persists on the latest version of the mod.
- [X] All version numbers are properly recorded, no instances of ‘latest’
- [X] All details are reported clearly and concisely
- [X] This issue is not a duplicate of another issue
- [X] If the issue is a modpack-related issue, it has been reported to the modpack devs as well

**Comment by Zepalesque** [comment] 2024-01-30 03:45
that’s odd, they should, I’ll fix this in v2.0

**Comment by Zepalesque** [comment] 2024-01-30 20:18
Actually hold on, you said _yagroot?_ Because yagroot is from a different addon, Deep Aether, so if you _meant_ to say yagroot you might want to report that to their issue tracker lol
https://github.com/RazorDevs/Deep-Aether/issues

**Comment by MoonMoonShark** [comment] 2024-02-01 20:04
let me double check. i know yagroot is one we were having trouble with, but i cut down trees all across the aether and the only ones that were dropping saplings came from the original aether, not from either aether: redux or deep aether.

ok, just took out a Glacia tree forest, and no saplings. those ones are labeled aether: redux.

made a field full of aether: redux trees, bonemealed them all, and broke them all. no saplings. (did the same with deep aether trees, so i'll be reporting those to them as well.)

**Comment by Zepalesque** [comment] 2024-02-12 23:46
strange, I can't seem to reproduce the issue
at any rate, it seems to be working in the next update I guess so once that releases it should be fixed
I may have fixed this unknowingly lol

**Comment by MoonMoonShark** [comment] 2024-02-13 00:57
you're so good, you don't even know it! :D you're my hero!

**Comment by Zepalesque** [comment] 2024-03-07 04:19
should be fixed in version 2.0, I plan to port 2.0 to 1.19.2 soon as well so it should be applicable there as well

**Closed as completed** 2024-03-07 04:20 UTC
Labels: bug-report, pending-update

**Comment by MoonMoonShark** [comment] 2024-03-21 20:53
you're a rock star. thank you so much!
