### ISSUE TITLE
World Creation Bug [1.19.2]: Game crashing upon finalizing a world creation/loading of an old one.

### ISSUE THREAD

**Issue by LifusChrustus** [Zepalesque/Aether-Redux-Issue-Tracker#27] opened 2023-11-05 09:43 UTC
**What version of the mod, Forge/Neoforge and Minecraft are you using?**

MC: 1.19.2
Forge: 43.2.21

**Describe the bug**
The game decides to crash when it finalizes new world creation/loading process of an old one.

**To Reproduce**
1. Start a new game.
2. Wait for it to generate.
3. Get a crash?

**Expected behavior**
Expected the game and server to load the world files and not crash :P

**Screenshots**
-------------------

**Crash report (if necessary and/or applicable)**
ex: https://pastebin.com/k9WWxJGH

**Log file (should be titled latest.log, if applicable)**
ex: https://pastebin.com/BKAgbpA3

**Additional context**
ex: Potential mod conflict?
Modlist used in testing: https://imgur.com/a/yB5A1Uy

**Comment by Zepalesque** [comment] 2023-11-05 21:50
Looking at your crash report, your Aether version seems to be out of date, so try updating to beta.1.3 (of the *Aether*, not of redux, redux appears to be up to date)

**Comment by LifusChrustus** [comment] 2023-11-05 21:56
Oh, my bad. Haven't notice that there was an update for the main mod. I'll check it when I can, thanks.

**Comment by Zepalesque** [comment] 2023-11-21 22:05
based on the fact that I’m about 99% sure this is caused by an older version being used, I’ll close this now

**Closed by Zepalesque** 2023-11-21 22:05 UTC
Labels: bug-report
