### ISSUE TITLE
[Bug]: Game crashes when disconnecting from server. ("Registry minecraft:item: Object did not get ID it asked for. Name: aether_redux:valkyrie_ring")

### ISSUE THREAD

**Issue by Gbergz** [Zepalesque/Aether-Redux-Issue-Tracker#109] opened 2024-05-12 13:23 UTC
### Minecraft Version

1.20.1

### Mod Version

2.0.12b

### Forge/Neoforge Version

47.2.17

### What happened?

When a player disconnects from a server they crash.

### What was the expected result?

No crash.

### Steps to Reproduce

Not entirely sure since most players reporting this have it happen when just leaving the server of theirs.

While myself I can't reproduce it, so it's a weird issue.

### Log Output (if applicable)

https://gist.githubusercontent.com/Gbergz/80f3b34147d70f044d4e80fdf57e4de8/raw/bc84e004a6082cceb234f2ef781e7195d62910cf/gistfile1.txt

### Crash Report (if applicable)

Crashlog from logs: 
https://gist.githubusercontent.com/Gbergz/80f3b34147d70f044d4e80fdf57e4de8/raw/bc84e004a6082cceb234f2ef781e7195d62910cf/gistfile1.txt

Generated crash report:
https://gist.githubusercontent.com/Gbergz/61baefcbe8d5fb29f0f0c7f0cc29dd08/raw/195fedf48925f685bf45fcced068f17f1f34020f/gistfile1.txt

### Is this a compatibility issue with another mod?

It very well could be, reporting here to make sure.

### Additional Context/Information

The only reason I am reporting it here is because every time this gets reported a specific thing in the logs sticks out.

This:
`Registry minecraft:item: Object did not get ID it asked for. Name: aether_redux:valkyrie_ring Expected: 31653 Got: 31648`

The Valkyrie Ring. 
And if I read correctly for your 2.0 version, this Ring was supposed to be removed? Maybe thats why this happens. Not sure to be honest.

Anyway, thanks in advance.
**-** Gbergz

### Make sure to confirm these as well before submitting the report:

- [X] The issue persists on the latest version of the mod.
- [X] All version numbers are properly recorded, no instances of ‘latest’
- [X] All details are reported clearly and concisely
- [X] This issue is not a duplicate of another issue
- [X] If the issue is a modpack-related issue, it has been reported to the modpack devs as well

**Comment by Zepalesque** [comment] 2024-05-12 20:08
hmm, that's really strange
was the world created in a pre-2.0 version? That could potentially be the issue, as while the valkyrie ring got removed in 2.0 I readded it a bit more recently, but yeah, not fully sure why this is happening

**Comment by Gbergz** [comment] 2024-05-14 13:46
Yes the world was created pre-2.0 I am pretty sure.
Sorry for late reply.

**Comment by Zepalesque** [comment] 2024-05-14 18:34
hmm, was it loaded into a version after 2.0 before using the newer one (2.0.12b)?
because I wonder if it could potentially be caused by the fact that the Valkyrie ring didn’t exist for a few versions, though I’m not sure why that’d cause *crashing* mind you but yeah that seems like a potential cause maybe, I’ll have to look into this at some point

**Comment by Gbergz** [comment] 2024-05-14 19:01
Followup on the question if the world was created pre 2.0, I was mistaken, it wasn't.
I made the world we're using on our servers with version 2.0.7d of Aether Redux.

**Comment by Zepalesque** [comment] 2024-05-14 23:11
oh, strange :thinking:
is the log included the *full* log, or just part of it? wondering because it seems shorter than logs usually are
if not, it'd be helpful if I could have that as the crash seems to mention checking the log for more info

**Comment by Gbergz** [comment] 2024-05-15 01:42
Its a part of the logs, there's no other errors in the log than that part.

**Comment by Zepalesque** [comment] 2024-05-15 01:46
well yeah but it could still be useful, it mentions this:
`One of more entry values did not copy to the correct id. Check log for details!`
but I'm not seeing it in the partial log, so having the full log would be helpful as it may not be an error in the log necessarily

**Comment by Gbergz** [comment] 2024-05-15 09:30
Of course, but currently I do not have the full log. 

The "Check log for details" is that part I am copying from and pasting to the link above.

Gonna have to try and reproduce the issue again and get you full logs then.

**Comment by Zepalesque** [comment] 2024-05-15 19:48
ah yeah that’s be helpful

**Comment by Gbergz** [comment] 2024-05-15 21:21
Here you go
https://gist.githubusercontent.com/Gbergz/1e2579ecc90c6912aac12ac705ef3481/raw/abc8e40c51d6d60d89d7caa2cf35bd26482a6b33/gistfile1.txt

File if needed: 
[latest.log](https://github.com/Zepalesque/The-Aether-Redux/files/15327131/latest.log)

**Comment by Zepalesque** [comment] 2024-05-16 17:51
hmm, do you have the crash report itself? the log unfortunately doesn't seem to have much more information lol

**Comment by Gbergz** [comment] 2024-05-17 10:38
The crash report has the same logs as on the bottom in the logs, kind of.

**Comment by Gbergz** [comment] 2024-05-17 10:39
And I did post the crash report in the initial report. 😅 Here it is again https://gist.githubusercontent.com/Gbergz/61baefcbe8d5fb29f0f0c7f0cc29dd08/raw/195fedf48925f685bf45fcced068f17f1f34020f/gistfile1.txt

**Comment by Zepalesque** [comment] 2024-05-28 21:02
hmm, I can’t seem to figure out this issue, it doesn’t make any sense why it’d be crashing
items getting different ids than they expect doesn’t usually cause crashes

**Comment by Gbergz** [comment] 2024-05-28 21:20
> Items getting different ids than they expect doesn’t usually cause crashes

I know right, super weird issue.

**Comment by Zepalesque** [comment] 2024-06-10 21:23
hmm, I have a potential idea to fix this, which involves renaming the item
I was *going* to do that in v2.1, but I could probably do it in 2.0.17 instead

**Comment by Gbergz** [comment] 2024-06-10 23:18
👀 hopefully that fixes it :)

**Comment by Zepalesque** [comment] 2024-07-18 13:50
should hopefully be fixed now, took a bit longer than I meant for it to lol

**Closed as completed by Zepalesque** 2024-07-18 13:50 UTC
Labels: bug-report

**Comment by Gbergz** [comment] 2024-07-18 15:06
Awesome, thanks!
