### ISSUE TITLE
[Bug]: >>Conflict with a mod<<

### ISSUE THREAD

**Issue by YEEERZZZ** [Zepalesque/Aether-Redux-Issue-Tracker#62] opened 2024-02-26 16:34 UTC
### Minecraft Version

1.20.1

### Mod Version

aether-redux-2.0-pre8-1.20.1-neoforge

### Forge/Neoforge Version

47.2.19

### What happened?

During use, conflicts arise with the "jade" mod, resulting in incomplete display of "jade" mod information. "Jade" mod Version: 11.8.0, forge, 1.20.1

### What was the expected result?

Enable the complete display of default settings for jade mod

### Steps to Reproduce

when I tried to use The Aether related mods, I found that when entering the game, the Jade mod displayed incomplete information about creatures or items. After troubleshooting, I found that it was due to this mod.

### Is this a compatibility issue with another mod?

Jade 🔍

### Make sure to confirm these as well before submitting the report:

- [X] The issue persists on the latest version of the mod.
- [X] All version numbers are properly recorded, no instances of ‘latest’
- [X] All details are reported clearly and concisely
- [X] This issue is not a duplicate of another issue
- [X] If the issue is a modpack-related issue, it has been reported to the modpack devs as well

**Comment by Zepalesque** [comment] 2024-02-26 16:38
Hmm, could you post a screenshot? I’m not fully sure what you mean

**Comment by YEEERZZZ** [comment] 2024-02-26 16:44
before
![before](https://github.com/Zepalesque/The-Aether-Redux/assets/122009562/50f59df1-1bed-4db8-982d-563101e1080d)

after
![after](https://github.com/Zepalesque/The-Aether-Redux/assets/122009562/04773736-29f6-4562-bfba-d202d4340e5b)

**Comment by Zepalesque** [comment] 2024-02-26 16:46
odd, yeah not sure why that’s happening
I’ll look into it

**Comment by Zepalesque** [comment] 2024-02-26 16:46
Actually hmm, could you post your mod list?

**Comment by YEEERZZZ** [comment] 2024-02-26 16:57
Oh, are you sure you need my mod list? It has 350+. I tried filtering through them one by one and found that this issue only occurred after using this mod

**Comment by Zepalesque** [comment] 2024-02-26 17:00
ah i see xd
yeah i was hoping I could try the same mods and see if I could figure out the cause, but yeah if it’s that much i don’t need to lol
but yeah redux does a tiny bit of stuff with jade so that may be part of what’s causing the issue
there may be a conflict with a jade addon or something, do you have any addons for jade installed?

**Comment by Zepalesque** [comment] 2024-02-26 17:01
also, it may be helpful to post your latest.log file, not certain it will have anything but if there are any errors occuring they may be logged there

**Comment by YEEERZZZ** [comment] 2024-02-26 17:06
Jade Addons! I suddenly realized that I forgot to install this, may it be because of this?

**Comment by Zepalesque** [comment] 2024-02-26 17:16
ah I meant that if you *did* have addons they may be conflicting, hmm
Could you post the latest.log file so I can see if there are any errors logging?

**Comment by YEEERZZZ** [comment] 2024-02-26 17:17
Okay, it's the same after installation XD.
[Uploading latest.log…]()

**Comment by YEEERZZZ** [comment] 2024-02-26 17:20
[Uploading debug.log…]()

**Comment by Zepalesque** [comment] 2024-02-26 17:22
ah you have to wait a moment for it to upload lol
it seems like you pressed comment before it could fully upload the log files

**Comment by YEEERZZZ** [comment] 2024-02-26 17:29
[latest.log](https://github.com/Zepalesque/The-Aether-Redux/files/14408212/latest.log)
[debug.log](https://github.com/Zepalesque/The-Aether-Redux/files/14408215/debug.log)
Oh, click fast, sorry, because I have to do something else

**Comment by Zepalesque** [comment] 2024-02-26 17:33
Ah I think I see the issue, yeah I’ll fix this for the next pre-release

**Comment by Zepalesque** [comment] 2024-02-26 19:08
heck i didn’t mean to close it yet

**Comment by Zepalesque** [comment] 2024-02-26 19:09
once I publish pre9 I’ll close this issue lol since it’ll be fixed

**Comment by Zepalesque** [comment] 2024-02-27 03:56
should be fixed now

**Closed as completed by Zepalesque** 2024-02-27 03:56 UTC
Labels: bug-report, pending-update

**Comment by YEEERZZZ** [comment] 2024-02-27 04:41
Great！
The display is normal now！
