### ISSUE TITLE
[Bug]: >>Crashing on client launch<<

### ISSUE THREAD

**Issue by DenisP-AC** [Zepalesque/Aether-Redux-Issue-Tracker#89] opened 2024-03-20 16:52 UTC
### Minecraft Version

1.19.2

### Mod Version

2.0.7 and 2.0.7b

### Forge/Neoforge Version

43.3.8

### What happened?

As soon as the launcher closes after pressing play, the game crashes and opens back the launcher. I don't know why this happens. After switching back to 1.3.4, everything is working.

### What was the expected result?

Game to be able to load.

### Steps to Reproduce

Use version 2.0.7 or 2.0.7b of the mod.
Maybe another mod is the problem?

### Log Output (if applicable)

[2024-03-20-7.log](https://github.com/Zepalesque/The-Aether-Redux/files/14669979/2024-03-20-7.log)

### Make sure to confirm these as well before submitting the report:

- [X] The issue persists on the latest version of the mod.
- [X] All version numbers are properly recorded, no instances of ‘latest’
- [X] All details are reported clearly and concisely
- [X] This issue is not a duplicate of another issue
- [X] If the issue is a modpack-related issue, it has been reported to the modpack devs as well

**Comment by Zepalesque** [comment] 2024-03-20 17:28
yeah, I'm pretty sure this is another mod causing the issue as when I try to load up the mod it works fine, but I'll look into it regardless

**Comment by DenisP-AC** [comment] 2024-03-20 17:37
I will try activating mod by mod from what I have installed to see where it breaks.

**Comment by Zepalesque** [comment] 2024-03-20 17:48
hmm actually testing now, I'm not 100% sure that it is a crash from another mod, I just had forgotten to try testing it in a non-dev environment which is why I couldn't reproduce the issue before
If you do find a mod that causes it though, let me know and I can look into fixing the issue for that, if not, then I should hopefully be able to fix this for 2.0.7c

**Comment by Lewda6336** [comment] 2024-03-20 22:28
Having the same issue with the 2.0 updates on 1.19.2. Some pointers i have noticed: Valkyrien skies appeared to be the culprit but after removing it the game starts but throws at me bunch of dependencies for mods that don't or didn't need them before (also some of the dependencies are not even available for Forge Mod Loader like Satin API) more in the screenshot:
![screen](https://github.com/Zepalesque/The-Aether-Redux/assets/142696384/efc422d2-f305-4bc7-bb56-e9e66d1400b3)

**Comment by Zepalesque** [comment] 2024-03-20 22:57
yeah I’m pretty sure the issue was a mismatched MixinExtras version, I’ll try to get a fix released pretty soon

**Comment by Zepalesque** [comment] 2024-03-21 02:34
should be fixed in 2.0.7c

**Closed as completed by Zepalesque** 2024-03-21 02:34 UTC
Labels: bug-report
