### ISSUE TITLE
[Bug]: Infused Viridium Pickaxe at 1 infusion causes client/server desync

### ISSUE THREAD

**Issue by nmarks413** [Zepalesque/Aether-Redux-Issue-Tracker#129] opened 2024-06-26 23:48 UTC
### Minecraft Version

1.20.1

### Mod Version

2.0.16c

### Forge/Neoforge Version

47.3.1

### What happened?

When mining with infused veridium pickaxe, blocks are destroyed and able to be picked up until 1 infusion level is left, but then blocks appear to be destroyed, and do not drop items. When another block is placed in the area, it reverts to the original state

### What was the expected result?

Block should be destroyed, and item should drop onto ground

### Steps to Reproduce

1) craft veridium pickaxe
2) infuse by right clicking with ambrosium shard
3) mine 7 times
4) attempt to mine another time

### Additional Context/Information

I am using the lastest version of better minecraft 4, so there could be a compatability issue there

### Make sure to confirm these as well before submitting the report:

- [X] The issue persists on the latest version of the mod.
- [X] All version numbers are properly recorded, no instances of ‘latest’
- [X] All details are reported clearly and concisely
- [X] This issue is not a duplicate of another issue
- [X] If the issue is a modpack-related issue, it only occurs *with* Redux installed, and not without
- [X] If the issue is a modpack-related issue, it has been reported to the modpack devs as well

**Comment by What-The-Cheick** [comment] 2024-06-27 22:59
This issue seems to be related to infused veridium in general, this crash has happened on a server with a veridium axe

**Comment by Zepalesque** [comment] 2024-07-04 22:16
oh jeez uh oh lol yeah
I was successfully able to reproduce this though which is good
I'll fix this in 2.0.17

**Comment by Zepalesque** [comment] 2024-07-18 13:50
should be fixed now

**Closed as completed by Zepalesque** 2024-07-18 13:50 UTC
Labels: bug-report, pending-update
