### ISSUE TITLE
[Bug]: >>overworld grass spawning in the aether<<

### ISSUE THREAD

**Issue by cassidyunderscore** [Zepalesque/Aether-Redux-Issue-Tracker#73] opened 2024-03-09 20:25 UTC
### Minecraft Version

1.20.1

### Mod Version

2.0.3

### Forge/Neoforge Version

47.2.0

### What happened?

when i updated aether redux and opened my survival world, there was regular overworld grass in the aether in places it was not before i logged off, also regular aether grass seems to be completely missing.
![grass](https://github.com/Zepalesque/The-Aether-Redux/assets/155733593/dd08974a-ba45-4a60-8e66-64d452a2395d)

### What was the expected result?

my world to be the same and regular aether grass to be growing.

### Steps to Reproduce

make a world on a previous update of aether redux and update to 2.0.

### Additional Context/Information

i want to add upon updating aether redux and logging into my world items were missing from my chests and a hole that was not previously there appeared in my cow farm.
![cow_death](https://github.com/Zepalesque/The-Aether-Redux/assets/155733593/cf4e9af7-0bf1-4b42-9731-1d57b97ed2ae)

also my enchanted gravitite has become worthless.

### Make sure to confirm these as well before submitting the report:

- [X] The issue persists on the latest version of the mod.
- [X] All version numbers are properly recorded, no instances of ‘latest’
- [X] All details are reported clearly and concisely
- [X] This issue is not a duplicate of another issue
- [X] If the issue is a modpack-related issue, it has been reported to the modpack devs as well

**Comment by Zepalesque** [comment] 2024-03-09 20:31
yeah unfortunately 2.0 and later breaks previously existing worlds
good to know that it doesn't just prevent you from opening the world though - I *may* be able to implement *partial* compatibility with existing worlds from 1.3.4 and under at some point

**Comment by Zepalesque** [comment] 2024-03-09 20:36
although for the grass issue, that's because the deep aether addon spawns vanilla grass (the aether on its own just uses regular grass, 1.3.4 had replaced *most* of them including ones from other addons, but there were a few I missed, 2.0 fixes that) since in the base mod the grass color is changed to aether color when on aether grass
Redux overrides this, as it implements its own grass system with tinting plus a seperate tall grass block, so that's why the grass is there

**Comment by cassidyunderscore** [comment] 2024-03-09 20:55
i see. thanks for the response.

**Comment by Zepalesque** [comment] 2024-03-15 22:58
closing as it’s an issue caused by upgrading that can’t really be fixed, and it doesn’t happen on new worlds

**Comment by Zepalesque** [comment] 2024-03-19 03:21
just noticed there’s more to this issue than the double tallgrass, the rest (missing items, blocks, etc) should be fixed in 2.0.7 so I’ll reopen it until then

**Comment by Zepalesque** [comment] 2024-03-20 02:37
missing stuff has been fixed in 2.0.7

**Closed as completed by Zepalesque** 2024-03-20 02:37 UTC
Labels: bug-report, pending-update
